server:
  port: 8081
spring:
  application:
    name: issue-feedback-system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/issue_feedback?useSSL=false
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

allow-api-list:
  # 此处填写允许角色访问的API
  # 请填写实际API
  student:
    - /api/issue-category
  teacher:
    - /api/issue-category
  dept-leader:
    - /api/issue-category
  school-leader:
    - /api/issue-category
  admin:
    - /api/system
    - /api/issue-category